import type { Position, Market, BundleSummary } from '../types'

export const mockPositions: Position[] = [
  {
    ticker: 'AAPL',
    name: 'Apple Inc.',
    shares: 50,
    avgCost: 178.25,
    currentPrice: 195.89,
    marketValue: 9794.5,
    gainLoss: 882.0,
    gainLossPercent: 9.9,
  },
  {
    ticker: 'TSLA',
    name: 'Tesla, Inc.',
    shares: 20,
    avgCost: 242.5,
    currentPrice: 218.75,
    marketValue: 4375.0,
    gainLoss: -475.0,
    gainLossPercent: -9.79,
  },
  {
    ticker: 'NVDA',
    name: 'NVIDIA Corporation',
    shares: 30,
    avgCost: 480.0,
    currentPrice: 875.35,
    marketValue: 26260.5,
    gainLoss: 11860.5,
    gainLossPercent: 82.4,
  },
  {
    ticker: 'MSFT',
    name: 'Microsoft Corporation',
    shares: 25,
    avgCost: 365.0,
    currentPrice: 415.2,
    marketValue: 10380.0,
    gainLoss: 1255.0,
    gainLossPercent: 13.76,
  },
  {
    ticker: 'META',
    name: 'Meta Platforms, Inc.',
    shares: 15,
    avgCost: 320.0,
    currentPrice: 505.75,
    marketValue: 7586.25,
    gainLoss: 2786.25,
    gainLossPercent: 58.05,
  },
]

export const mockMarkets: Market[] = [
  {
    id: 'nvda-1',
    title: 'Will NVIDIA maintain >70% GPU market share in AI?',
    image: 'https://upload.wikimedia.org/wikipedia/sco/thumb/2/21/Nvidia_logo.svg/351px-Nvidia_logo.svg.png',
    confidence: 74,
    volume: 4100000,
    endDate: '2026-06-30',
    category: 'Tech',
    url: '#',
    relatedTickers: ['NVDA'],
  },
  {
    id: 'tsla-1',
    title: 'Will Tesla deliver 2M+ vehicles in 2026?',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Tesla_Motors.svg/279px-Tesla_Motors.svg.png',
    confidence: 35,
    volume: 5200000,
    endDate: '2026-12-31',
    category: 'Business',
    url: '#',
    relatedTickers: ['TSLA'],
  },
  {
    id: 'export-1',
    title: 'Will US impose new AI chip export restrictions in 2026?',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_the_United_States_%28DoS_ECA_Color_Standard%29.svg/383px-Flag_of_the_United_States_%28DoS_ECA_Color_Standard%29.svg.png',
    confidence: 45,
    volume: 6700000,
    endDate: '2026-12-31',
    category: 'Politics',
    url: '#',
    relatedTickers: ['NVDA', 'AAPL', 'MSFT'],
  },
  {
    id: 'aapl-1',
    title: 'Will Apple release a foldable device in 2026?',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Apple_logo_black.svg/195px-Apple_logo_black.svg.png',
    confidence: 22,
    volume: 1250000,
    endDate: '2026-12-31',
    category: 'Tech',
    url: '#',
    relatedTickers: ['AAPL'],
  },
  {
    id: 'aapl-2',
    title: 'Will Apple stock be above $200 by end of Q2 2026?',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Apple_logo_black.svg/195px-Apple_logo_black.svg.png',
    confidence: 68,
    volume: 3400000,
    endDate: '2026-06-30',
    category: 'Crypto',
    url: '#',
    relatedTickers: ['AAPL'],
  },
  {
    id: 'tsla-2',
    title: 'Will Tesla Robotaxi launch commercially in 2026?',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Tesla_Motors.svg/279px-Tesla_Motors.svg.png',
    confidence: 18,
    volume: 2800000,
    endDate: '2026-12-31',
    category: 'Tech',
    url: '#',
    relatedTickers: ['TSLA'],
  },
  {
    id: 'msft-1',
    title: 'Will Microsoft Copilot reach 100M paid users by 2026?',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Microsoft_logo.svg/240px-Microsoft_logo.svg.png',
    confidence: 42,
    volume: 2300000,
    endDate: '2026-12-31',
    category: 'Tech',
    url: '#',
    relatedTickers: ['MSFT'],
  },
  {
    id: 'msft-2',
    title: 'Will Microsoft stock outperform the S&P 500 in H1 2026?',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Microsoft_logo.svg/240px-Microsoft_logo.svg.png',
    confidence: 55,
    volume: 1800000,
    endDate: '2026-06-30',
    category: 'Crypto',
    url: '#',
    relatedTickers: ['MSFT'],
  },
  {
    id: 'meta-1',
    title: 'Will Meta launch a standalone AI product in 2026?',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Meta_Platforms_Inc._logo.svg/320px-Meta_Platforms_Inc._logo.svg.png',
    confidence: 61,
    volume: 3900000,
    endDate: '2026-12-31',
    category: 'Tech',
    url: '#',
    relatedTickers: ['META'],
  },
  {
    id: 'meta-2',
    title: 'Will Meta Reality Labs become profitable in 2026?',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Meta_Platforms_Inc._logo.svg/320px-Meta_Platforms_Inc._logo.svg.png',
    confidence: 12,
    volume: 2100000,
    endDate: '2026-12-31',
    category: 'Business',
    url: '#',
    relatedTickers: ['META'],
  },
  {
    id: 'fed-1',
    title: 'Will the Fed cut interest rates before July 2026?',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_the_United_States_%28DoS_ECA_Color_Standard%29.svg/383px-Flag_of_the_United_States_%28DoS_ECA_Color_Standard%29.svg.png',
    confidence: 58,
    volume: 8900000,
    endDate: '2026-07-01',
    category: 'Politics',
    url: '#',
    relatedTickers: ['AAPL', 'TSLA', 'NVDA', 'MSFT', 'META'],
  },
  {
    id: 'ai-1',
    title: 'Will an AI model pass a bar exam with top 10% score in 2026?',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/ChatGPT_logo.svg/240px-ChatGPT_logo.svg.png',
    confidence: 71,
    volume: 3200000,
    endDate: '2026-12-31',
    category: 'AI',
    url: '#',
    relatedTickers: ['NVDA', 'MSFT', 'META'],
  },
]

export const CATEGORIES = [
  'All',
  'Trending',
  'Tech',
  'Politics',
  'AI',
  'Crypto',
  'Business',
  'Sports',
]

export const SORT_OPTIONS = [
  'Trending',
  'Volume',
  'Newest',
  'Ending Soon',
  'Competitive',
]

export const mockBundleSummary: BundleSummary = {
  explanation:
    'This bundle pairs your tech-heavy stock positions with prediction markets that track key catalysts — product launches, regulatory shifts, and competitive dynamics — that could materially impact your holdings.',
  riskCovered:
    'Regulatory risk from potential AI chip export bans, execution risk from Tesla delivery targets, and valuation risk from Meta\'s continued Reality Labs spending.',
  hedgeRationale:
    'By taking positions in related prediction markets, you gain exposure to the specific event outcomes that drive your portfolio risk. If a negative catalyst materializes, your prediction market positions can offset stock losses.',
}
